In [1]:
import numpy as np

In [2]:
#1
a = np.array([12,13,12,15,16,18,12,10,11,19])
a = a.reshape(5,2)
print(a)

[[12 13]
 [12 15]
 [16 18]
 [12 10]
 [11 19]]


In [4]:
#2
arr = np.array([1,3,4,8,9,3,1,7,4,8,9,10])
np.unique(arr)

array([ 1,  3,  4,  7,  8,  9, 10])

In [5]:
#3
P = np.tile( np.array([[0,1],[1,0]]),(5,5))
P[1:-1,1:-1] = 7
print(P)

[[0 1 0 1 0 1 0 1 0 1]
 [1 7 7 7 7 7 7 7 7 0]
 [0 7 7 7 7 7 7 7 7 1]
 [1 7 7 7 7 7 7 7 7 0]
 [0 7 7 7 7 7 7 7 7 1]
 [1 7 7 7 7 7 7 7 7 0]
 [0 7 7 7 7 7 7 7 7 1]
 [1 7 7 7 7 7 7 7 7 0]
 [0 7 7 7 7 7 7 7 7 1]
 [1 0 1 0 1 0 1 0 1 0]]


In [12]:
#4
a1 = np.array([[4,3],[3,6]])
a2 = np.array([[2,1],[4,5]])
s = np.dot(a1, a2)
print(s)

[[20 19]
 [30 33]]
