In [2]:
import numpy as np            #importing numpy

Create a null vector of size 10

In [16]:
Z = np.zeros(10)
print(Z)


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [19]:
z= np.ones(5)
print(z)

[1. 1. 1. 1. 1.]


Create a null vector of size 10 but the fifth value which is 1

In [22]:
Z = np.zeros(10)
Z[4] = 6
Z[6] = 9
print(Z)

[0. 0. 0. 0. 6. 0. 9. 0. 0. 0.]


create an array ranging from 0 to 10 with middle value 50, reverse the array

In [24]:
z=np.arange(0,11)
z[4]=50
z=z[::-1]
z

array([10,  9,  8,  7,  6,  5, 50,  3,  2,  1,  0])

 Create a vector with values ranging from 10 to 49 

In [4]:
Z = np.arange(10,50)                      #Arranging array with given range
print(Z)


[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


 Reverse a vector (first element becomes last)

In [36]:
Z = np.arange(51)
Z = Z[::-1]
print(Z)

[50 49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27
 26 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3
  2  1  0]


 Create a 3x3 matrix with values ranging from 0 to 8

In [33]:
z=np.arange(41,51).reshape(5,2)          #creating matrix
print(z)
z=z[::-1]                                  #reverse the matrix
print(z)

[[41 42]
 [43 44]
 [45 46]
 [47 48]
 [49 50]]
[[49 50]
 [47 48]
 [45 46]
 [43 44]
 [41 42]]


In [35]:
a=np.arange(1,16).reshape(5,3)
a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [26]:
Z = np.arange(1,10).reshape(3,3)
print(Z)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


 Create a 10x10 identity matrix

In [39]:
Z = np.eye(10,10)
print(Z)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


Create a 5x3x2 array with random values

In [45]:
Z = np.random.random((5,3,2)) #(1st no,2nd no, 3rdno)-1st- Number of matrices, 2nd and 3rd forms rows and columns
Zmin = Z.min()
Zmax = Z.max()
print(Z)
print(Zmin)
print(Zmax)

[[[0.66825409 0.85681313]
  [0.02187884 0.75962967]
  [0.10365977 0.48974802]]

 [[0.29766593 0.54596894]
  [0.29698609 0.6952479 ]
  [0.38263868 0.6390706 ]]

 [[0.4945445  0.77071823]
  [0.45117423 0.01596888]
  [0.67908848 0.35374051]]

 [[0.75234721 0.51212852]
  [0.83121545 0.12915679]
  [0.65594286 0.8341798 ]]

 [[0.63334569 0.92857063]
  [0.18586322 0.36268915]
  [0.90820936 0.20086956]]]
0.015968882749885394
0.9285706282932568


Create a 3x3 array with random values and find the minimum and maximum
values, mean value

In [48]:
Z = np.random.random((3,3))
print(Z)
Zmin, Zmax = Z.min(), Z.max()
Zmean = Z.mean()
print(Zmin)
print(Zmax)
print(Zmean)


[[0.11647691 0.31756103 0.88470232]
 [0.40768251 0.71205184 0.58215493]
 [0.02823626 0.73339035 0.35051583]]
0.028236262371979404
0.8847023200507783
0.45919688668557423


 Create a random vector of size 30 and find the mean value

In [47]:
Z = np.random.random(30)
print(Z)
m = Z.mean()
print(m)

[0.70479916 0.53461166 0.8995509  0.67345815 0.0179103  0.05280211
 0.31888956 0.05748206 0.02208575 0.46809165 0.12234038 0.44834999
 0.19054441 0.82907953 0.58694125 0.95948708 0.34415094 0.8096632
 0.60429893 0.83617958 0.0541026  0.47945368 0.37383274 0.57466687
 0.94101285 0.1368231  0.54053111 0.16609876 0.47624886 0.41722351]
0.45469035537129365


Create a 2d array with 1 on the border and 0 inside

In [54]:
Z = np.ones((10,10))
Z
Z[1:-1,1:-1] = 8
print(Z)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 8. 8. 8. 8. 8. 8. 8. 8. 1.]
 [1. 8. 8. 8. 8. 8. 8. 8. 8. 1.]
 [1. 8. 8. 8. 8. 8. 8. 8. 8. 1.]
 [1. 8. 8. 8. 8. 8. 8. 8. 8. 1.]
 [1. 8. 8. 8. 8. 8. 8. 8. 8. 1.]
 [1. 8. 8. 8. 8. 8. 8. 8. 8. 1.]
 [1. 8. 8. 8. 8. 8. 8. 8. 8. 1.]
 [1. 8. 8. 8. 8. 8. 8. 8. 8. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [ ]:
Z = np.ones((10,10))

Z[0:5] = 0
print(Z)


In [55]:
Z = np.ones((10,10))

Z[0:5] = 0
print(Z)


[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [63]:
Z = np.ones((10, 10)) 
Z[0:-4]=0
print(Z)
z[0:4]=0
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [58]:
Z = np.ones((10,10))

Z[5:] = 0
print(Z)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [64]:
Z = np.ones((10,10))
Z[1:-1,1:-1] = 0
print(Z)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


 Create a checkerboard 8x8 matrix using the tile function

In [69]:
a = np.tile(np.array([[0,1],[1,0],(2,2)])
print(a)

SyntaxError: invalid syntax (<ipython-input-69-063f8559223e>, line 2)

In [72]:
Z=np.array([0,1],[1,0])
Z

TypeError: data type not understood

In [70]:
Z=np.array([0,1],[1,0])

Z = np.tile( np.array([[0,1],[1,0]]),(2,2))
print(Z)

[[0 1 0 1]
 [1 0 1 0]
 [0 1 0 1]
 [1 0 1 0]]


In [71]:
Z = np.tile( np.array([[0,1],[1,0]]),(4,4))
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [73]:
Z = np.tile( np.array([[0,0],[1,1]]),(4,4))
print(Z)

[[0 0 0 0 0 0 0 0]
 [1 1 1 1 1 1 1 1]
 [0 0 0 0 0 0 0 0]
 [1 1 1 1 1 1 1 1]
 [0 0 0 0 0 0 0 0]
 [1 1 1 1 1 1 1 1]
 [0 0 0 0 0 0 0 0]
 [1 1 1 1 1 1 1 1]]


Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)

In [52]:
Z = np.dot(np.ones((5,3)), np.ones((3,2)))
print(Z)


[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


In [74]:
Z = np.dot(np.ones((5,3)), np.zeros((3,2)))
print(Z)


[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


Consider an array of dimension (5,5,3), how to mulitply it by an array with
dimensions (5,5)

In [76]:
A = np.ones((5,5,3))
print(A)
B = 2*np.ones((5,5))
print(B)
print(A * B[:,:,None])

[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]
[[2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]]
[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


How to swap two rows of an array

In [77]:
A = np.arange(25).reshape(5,5)
print(A)
A[[1,2]] = A[[2,1]]
print(A)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[[ 0  1  2  3  4]
 [10 11 12 13 14]
 [ 5  6  7  8  9]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [78]:
A = np.arange(25).reshape(5,5)
print(A)
A[[0,4]] = A[[4,0]]
print(A)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[[20 21 22 23 24]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [ 0  1  2  3  4]]


How to find the most frequent value in an array

In [90]:
Z = np.random.randint(50,100,30) #range 0 to 10 , with 50 values
print(Z)
print(np.bincount(Z).argmax())

[71 97 67 67 69 78 64 72 95 89 94 80 61 75 75 70 88 75 53 83 62 89 70 89
 93 69 53 81 93 81]
75


In [63]:
Z = np.random.randint(0,10,50) #range 0 to 10 , with 50 values
print(Z)
print(np.bincount(Z).argmax())

[2 7 6 5 4 7 4 3 2 7 6 2 0 5 7 5 3 9 7 3 4 4 4 3 1 9 3 7 6 7 1 5 1 6 8 8 5
 8 8 7 0 3 9 5 5 9 0 8 0 8]
7


 How to get the n largest values of an array

In [93]:
Z = np.arange(100)
np.random.shuffle(Z)
n = 20
# Slow
print (Z[np.argsort(Z)[-n:]])



[80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99]


 How to create a record array from a regular array

In [30]:
Z = np.array([("Hello", 2.5, 3),("World", 3.6, 2)])
print(Z)
R = np.core.records.fromarrays(Z.T,names='col1, col2, col3',formats = 'S8, f8, i8')
                                
                                         
print(R)

[['Hello' '2.5' '3']
 ['World' '3.6' '2']]
[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]


In [92]:
r=np.core.records.fromrecords([(456,'dbe',1.2),(2,'de',1.3)],names='col1,col2,col3')
print(r)
print(r[0])

print(r.col1)

print(r.col2)


[(456, 'dbe', 1.2) (  2, 'de', 1.3)]
(456, 'dbe', 1.2)
[456   2]
['dbe' 'de']
